### ISSUE TITLE
Untrimmed links in DB when adding new items, also raw table doesn't populate when items are added EMU and LIVE 

### ISSUE THREAD

**Issue by grimmier378** [RedGuides/MQ2LinkDB#10]
Issue 1: when new items are added to the DB they do not populate their name and id into the raw table. which is joined to the link table for lookups. 

Issue 2: if the line an new item is pulled from has more text after the item link it will add all of that into the link table with the link. 

Expected behavior: When a new item is added to the DB the link should be trimmed to the items link, and the id and name should populate the raw table so you can lookup items by name.

Image from Live empty table after adding 3 items linked in one say. 
![image](https://github.com/user-attachments/assets/4c98f2fa-b308-4c8c-a6c5-b5525abe06d3)

Image from EMU same style test.

![image](https://github.com/user-attachments/assets/22094cec-3ab9-4b44-8e05-c931b45b6215)

**Comment by brainiac** [comment]
this isn't a linkdb bug.

**Comment by brainiac** [comment]
This needs to be fixed in core mq or it will just keep happening. Fix the cause not the symptom

**Comment by brainiac** [comment]
followup: ended up being a bug elsewhere in linkdb
